name: what_app
description: WhatsApp Clone

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0
  dio: ^4.0.6
  country_picker: ^2.0.19
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  flutter_riverpod: ^2.1.3
  go_router: ^6.0.0
  image_picker: ^0.8.6
  permission_handler: ^10.2.0
  firebase_storage: ^11.0.10
  flutter_contacts: ^1.1.5+1
  cloud_firestore: ^4.3.1
  firebase_database: ^10.0.9
  uuid: any
  intl: any
  shimmer: ^2.0.0
  custom_clippers: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# flutter launcher icon
flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true

#flutter_native_splash
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#111B21"
  image: "assets/images/splash_light.png"
  image_dark: "assets/images/splash_dark.png"
  android12:
    color: "#FFFFFF"
    color_dark: "#111B21"
    image: "assets/images/splash_light.png"
    image_dark: "assets/images/splash_dark.png"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#111B21"


flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    #- assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
